### ISSUE TITLE
idrall submodule points to a wrong commit

### ISSUE THREAD

**Issue by JankaGramofonomanka** [idris-community/inigo#36]
I tried to build the project, following the README, and I could not build the `idrall` submodule. When I updated it to the latest commit  (13ef174), it worked.

**Comment by alexhumphreys** [comment]
https://github.com/idris-community/inigo/pull/34 Aye there's a PR to update it here. Though it's been a while, I probably have to bump the version again

**Comment by alexhumphreys** [comment]
this should be fixed on main thanks to https://github.com/idris-community/inigo/pull/38, can you try again and see if it works?

**Comment by JankaGramofonomanka** [comment]
I tried again and it works.
