### ISSUE TITLE
lambdaRequire has been removed from Idris 2

### ISSUE THREAD

**Issue by michaelmesser** [idris-community/inigo#7]
https://github.com/idris-community/inigo/blob/1d05cea0b0a45d9728514150f97f8b8f1c2ba9c9/Inigo/Async/Util.idr#L19
See https://github.com/idris-lang/Idris2/pull/873

**Comment by hayesgm** [comment]
Thanks-- will work on updating this.

**Comment by andylokandy** [comment]
This should be fixed by https://github.com/idris-community/inigo/pull/9

**Comment by hayesgm** [comment]
Thanks
